---
verbose: False

smarttub:
  username: 'smarttub_username'
  password: 'smarttub_password'

influxdb:
  username: 'influx_usernamehere'
  password: 'influx_usernamepassword'
  host: 'localhost'
  port: '8086'
  retention_policy: 'autogen'
  db_name: 'db_namehere'

logging:
  logger_name: "smarttub2influx"
  log_config: "/usr/local/smarttub2influx/config/logging.yml"
